[tools]
go = "latest"
"go:github.com/nats-io/nats-server/v2" = "main"
"go:github.com/nats-io/natscli/nats" = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"

[env]
GOOSE_DRIVER = "sqlite3"
GOOSE_DBSTRING = "file:local.db"
GOOSE_MIGRATION_DIR = "migrations"

[tasks.posting]
description = "open posting with project collection"
run = "posting --collection posting/"

[tasks.nats]
description = "run nats backing server"
run = "nats-server --config nats.conf -DV"
